draft faq, schedule, and tracks section
slohacks/slo-hacks-2019 pull request #16
Opened 2018-09-14 03:15 UTC by Jumer-Caragay

- Refactored schedule and faq to use json data.
- Refactored layouts and sections to utilize margin and padding for layouts instead of blank rows.
- Created the first draft for FAQ, schedule, baker, and tracks.

2018-09-16 13:16 UTC, selynna requested changes

2018-09-16 13:16 UTC, selynna commented on src/components/Schedule.jsx
> +        <section className={styles.scheduleSection}>
There should be 3 schedule sections - Friday, Saturday, Sunday

2018-09-16 13:16 UTC, selynna commented on src/components/FAQ.jsx
> +          <Column >
whitespace after column

2018-09-16 13:16 UTC, selynna commented on src/components/FAQ.module.css
> +  '. header .'
weren't we supposed to get rid of the whitespace? or are you going to change it later?

2018-09-16 13:16 UTC, selynna commented on src/components/FAQ.module.css
> +  background-color: rgba(135,224,225, .7);
can you space out the rgba like 135, 224, etc instead of it without the spaces

2018-09-16 13:16 UTC, selynna commented on src/components/History.jsx
> +        <Header fontSize="4.5rem" color="#67778e">We Are SLO <br />Hacks.</Header>
instead of doing a <br>, is there a way we could limit the size of the header to ensure it goes onto the next line? on mobile it won't necessarily be we are slo \n hacks

2018-09-16 13:16 UTC, selynna commented on src/components/History.module.css
> +  '. historyHeader historyText .';
same question about whitespace here - are you going to change it to margins at a later date?

2018-09-16 13:16 UTC, selynna commented on src/components/common/Button.jsx
> +  borderRadius,
remove comma at end?

2018-09-16 13:16 UTC, selynna commented on src/components/common/Button.jsx
> +    borderRadius,
remove comma here as well?

2018-09-17 03:21 UTC, Jumer-Caragay commented on src/components/FAQ.module.css
> +  '. header .'
The refactor for the whitespace in the grid was removing rows that created the whitespace vertically. Margins and padding will handle any whitespace vertically

2018-09-17 03:22 UTC, Jumer-Caragay commented on src/components/common/Button.jsx
> +  borderRadius,
My ESLint says that the comma at the end is required.

2018-09-17 03:28 UTC, Jumer-Caragay commented on src/components/Schedule.jsx
> +        <section className={styles.scheduleSection}>
I wasn't sure to add the third section yet since it isn't on the mockup, but I can add it in

2018-09-17 04:26 UTC, selynna commented on src/components/common/Button.jsx
> +  borderRadius,
oh interesting, ok!

2018-09-17 04:26 UTC, selynna commented on src/components/Schedule.jsx
> +        <section className={styles.scheduleSection}>
up to you! i'll follow up with you over slack regarding that

2018-09-17 04:43 UTC, Jumer-Caragay commented on src/components/History.jsx
> +        <Header fontSize="4.5rem" color="#67778e">We Are SLO <br />Hacks.</Header>
I haven't thought of a solution atm, but i'll look into our other websites that might have a solution to this.

2018-09-17 04:47 UTC, selynna commented on src/components/History.jsx
> +        <Header fontSize="4.5rem" color="#67778e">We Are SLO <br />Hacks.</Header>
@Jumer-Caragay this might help: https://css-tricks.com/almanac/properties/o/overflow-wrap/

2018-09-17 04:51 UTC, selynna approved these changes

2018-09-17 04:52 UTC, merged