feat(SponsorLogos.*, assets): add new sponsor logos
slohacks/slo-hacks-2019 pull request #53
Opened 2019-01-03 00:08 UTC by stonewallstan

2019-01-10 09:10 UTC, stonewallstan commented
![image](https://user-images.githubusercontent.com/16230045/50957900-44877280-1474-11e9-8050-499075323b41.png)
![image](https://user-images.githubusercontent.com/16230045/50957926-536e2500-1474-11e9-9d09-056856ebcd31.png)
![image](https://user-images.githubusercontent.com/16230045/50958005-84e6f080-1474-11e9-8f0c-bd254896165a.png)
![image](https://user-images.githubusercontent.com/16230045/50958025-94663980-1474-11e9-9e69-167db1a2ac42.png)

2019-01-11 00:30 UTC, selynna requested changes
A lot of these logo rows aren't equal

2019-01-11 00:30 UTC, selynna commented
![image](https://user-images.githubusercontent.com/7741746/51005765-00888200-14f5-11e9-9c9d-a96a8a5b758a.png)

2019-01-11 00:31 UTC, selynna commented
![image](https://user-images.githubusercontent.com/7741746/51005789-2ada3f80-14f5-11e9-98be-70b8504f96b5.png)

2019-01-12 20:22 UTC, stanleyarmstrong commented
![image](https://user-images.githubusercontent.com/16230045/51078071-97278100-1664-11e9-9baf-138dd21f0ebd.png)
![image](https://user-images.githubusercontent.com/16230045/51078080-ad354180-1664-11e9-9e20-ef9be78ddac0.png)

Updated view of sponsors on desktop and mobile

2019-01-13 02:27 UTC, stanleyarmstrong commented
![image](https://user-images.githubusercontent.com/16230045/51080842-a96ee280-1697-11e9-9183-a40151b8eea1.png)
![image](https://user-images.githubusercontent.com/16230045/51080846-b7246800-1697-11e9-9c06-02d1149386ea.png)

2019-01-13 02:31 UTC, selynna commented
@stonewallstan still needs fixes 
![image](https://user-images.githubusercontent.com/7741746/51080880-4c276100-1698-11e9-83cc-22fdca980b98.png)

2019-01-13 02:35 UTC, selynna commented
Additionally, can you resolve the checks? It's an issue with the stylelint package again.

2019-01-13 02:36 UTC, selynna commented on src/assets/logos/wd-temp.svg
> +<?xml version="1.0" encoding="utf-8"?>
why are we using a temp file? is there no logo file provided from @jason-ngu?

2019-01-13 02:36 UTC, selynna commented on src/components/SponsorLogos.jsx
> +import wdtemp from '../assets/logos/wd-temp.svg';
same question about temp file here

2019-01-13 02:36 UTC, selynna commented on src/components/SponsorLogos.jsx
> +        <img className={styles.topLogo} src={itrade} alt="itradenetwork" />
alt -> iTradeNetwork

2019-01-13 02:37 UTC, selynna commented on src/components/SponsorLogos.jsx
> +        <img className={styles.medLogo} src={viasat} alt="viasat" />
Your alt's aren't consistent. Most of the ones above are capitalized properly, but this one isn't, and same with only some of them below.

2019-01-13 02:37 UTC, selynna commented on src/components/SponsorLogos.jsx
> +        <img className={styles.medLogo} src={godaddy} alt="godaddy" />
same prob with alt here

2019-01-13 02:37 UTC, selynna commented on src/components/SponsorLogos.jsx
> +        <img className={styles.medLogo} src={micro} alt="micro" />
same problem with alt

2019-01-13 02:37 UTC, selynna commented on src/components/SponsorLogos.jsx
> +        <img className={styles.medLogo} src={platinum} alt="Platinum Performance" />
same problem with alt

2019-01-13 02:38 UTC, selynna commented on src/components/SponsorLogos.jsx
> +      <a href="https://www.stickermule.com/" target="_blank" rel="noopener noreferrer">
update link to https://www.stickermule.com/uses/laptop-stickers

2019-01-13 02:39 UTC, stonewallstan commented on src/assets/logos/wd-temp.svg
> +<?xml version="1.0" encoding="utf-8"?>
Yeah, there's no file provided from @jason-ngu

2019-01-13 02:40 UTC, stonewallstan commented on src/assets/logos/wd-temp.svg
> +<?xml version="1.0" encoding="utf-8"?>
So I made it clear in the code that the file is only supposed to be there temporarily

2019-01-13 02:40 UTC, selynna commented on src/components/SponsorLogos.module.css
> +    grid-template-areas: 'f5 f5 f5 f5 wdtemp wdtemp wdtemp wdtemp itrade itrade itrade itrade';
so the logo distribution looks really funky because you're allocating the same amount of grid area to f5 as you are with wd and itrade, which have significantly longer logos. have you tried seeing what it looks like if you do 2fr for f5 and 5 for wd and itrade?

2019-01-13 02:41 UTC, selynna commented on src/assets/logos/wd-temp.svg
> +<?xml version="1.0" encoding="utf-8"?>
Cool, sounds good. I'll ping Jason in #sponsorship for you to get an updated WD logo.

2019-01-13 02:42 UTC, stonewallstan commented on src/components/SponsorLogos.module.css
> +    grid-template-areas: 'f5 f5 f5 f5 wdtemp wdtemp wdtemp wdtemp itrade itrade itrade itrade';
I'll look into it.

2019-01-13 02:44 UTC, selynna commented
So an overarching thing I'm seeing is that your alts for image files aren't consistent. Some of them are capitalized, although the majority of them are overwhelming are lowercase/abbreviated. Can we make the alts the formal company name with proper capitalization?

2019-01-15 14:09 UTC, selynna commented
The entire website is breaking (scroll left). Prob some universal padding/margin? 

There's still a lot of issues with the alignment of the logos (not aligned vertically, viasat still squished, etc). 
![image](https://user-images.githubusercontent.com/7741746/51185458-07641b80-188c-11e9-8005-9b3b00d696ae.png)

2019-01-16 23:47 UTC, selynna approved these changes

2019-01-16 23:47 UTC, merged